"""create_db

Revision ID: 263d92c47c4b
Revises: 
Create Date: 2023-03-28 11:07:20.311813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263d92c47c4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rubrics', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
